apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
spec:
  restartPolicy: Never
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=https://github.com/jmontalvof/microservicio-ejemplo.git#main"
        - "--destination=docker.io/jmontalvof/kaniko-test:latest"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config

